"""Fixed Balance model constraints

Revision ID: 751f3c275629
Revises: 
Create Date: 2025-04-16 09:00:49.840409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751f3c275629'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.drop_constraint('_wallet_coin_uc', type_='unique')
        batch_op.create_index(batch_op.f('ix_balance_cryptocurrency_type'), ['cryptocurrency_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_wallet_address'), ['wallet_address'], unique=False)
        batch_op.create_unique_constraint('uix_balance_wallet_crypto', ['wallet_address', 'cryptocurrency_type'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_receiver_address'), ['receiver_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_receiver_username'), ['receiver_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_sender_address'), ['sender_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_sender_username'), ['sender_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_timestamp'))
        batch_op.drop_index(batch_op.f('ix_transaction_sender_username'))
        batch_op.drop_index(batch_op.f('ix_transaction_sender_address'))
        batch_op.drop_index(batch_op.f('ix_transaction_receiver_username'))
        batch_op.drop_index(batch_op.f('ix_transaction_receiver_address'))

    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.drop_constraint('uix_balance_wallet_crypto', type_='unique')
        batch_op.drop_index(batch_op.f('ix_balance_wallet_address'))
        batch_op.drop_index(batch_op.f('ix_balance_cryptocurrency_type'))
        batch_op.create_unique_constraint('_wallet_coin_uc', ['wallet_address', 'cryptocurrency_type'])

    # ### end Alembic commands ###
